# Generated by Django 3.0.2 on 2020-01-27 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_catalog_product'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='catalog',
            constraint=models.UniqueConstraint(fields=('market', 'product'), name='unique_product_per_market'),
        ),
    ]
