# Generated by Django 3.0.2 on 2020-01-27 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200127_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketevent',
            name='name',
            field=models.CharField(default='name', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='marketevent',
            name='address',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
