# Generated by Django 3.0.2 on 2020-01-29 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200127_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=1000)),
                ('day_open', models.CharField(blank=True, choices=[('MO', 'Lunes'), ('TU', 'Martes'), ('WE', 'Miércoles'), ('TH', 'Jueves'), ('FR', 'Viernes'), ('SA', 'Sábado'), ('SU', 'Domingo')], max_length=2)),
                ('day_close', models.CharField(blank=True, choices=[('MO', 'Lunes'), ('TU', 'Martes'), ('WE', 'Miércoles'), ('TH', 'Jueves'), ('FR', 'Viernes'), ('SA', 'Sábado'), ('SU', 'Domingo')], max_length=2)),
                ('time_open', models.TimeField(blank=True)),
                ('time_close', models.TimeField(blank=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Vendor')),
            ],
        ),
        migrations.AlterField(
            model_name='catalog',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Market'),
        ),
        migrations.DeleteModel(
            name='MarketEvent',
        ),
    ]
