# Generated by Django 3.0.2 on 2020-01-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200129_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='day_close',
            field=models.CharField(choices=[('MO', 'Lunes'), ('TU', 'Martes'), ('WE', 'Miércoles'), ('TH', 'Jueves'), ('FR', 'Viernes'), ('SA', 'Sábado'), ('SU', 'Domingo')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='day_open',
            field=models.CharField(choices=[('MO', 'Lunes'), ('TU', 'Martes'), ('WE', 'Miércoles'), ('TH', 'Jueves'), ('FR', 'Viernes'), ('SA', 'Sábado'), ('SU', 'Domingo')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='time_close',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='time_open',
            field=models.TimeField(null=True),
        ),
    ]
